/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 18-3月-2018 01:07:55 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS `T_S_User` CASCADE
;

/* Create Tables */

CREATE TABLE `T_S_User`
(
	`c_id` VARCHAR(50) NOT NULL,
	`c_user_code` VARCHAR(50) NOT NULL COMMENT '用户代码',
	`c_user_name` VARCHAR(50) COMMENT '用户名称',
	`c_nick_name` VARCHAR(50) COMMENT '昵称',
	`c_user_pwd` VARCHAR(50) COMMENT '密码',
	`c_dv_state` VARCHAR(50) COMMENT '状态',
	`c_dv_card_type` VARCHAR(50) COMMENT '证件类型',
	`c_card_code` VARCHAR(50) COMMENT '证件号码',
	`c_email` VARCHAR(50),
	`c_native_place` VARCHAR(200) COMMENT '籍贯',
	`c_living_place` VARCHAR(200) COMMENT '现居地',
	`c_create_time` VARCHAR(25) COMMENT '注册时间',
	`c_user_sex` VARCHAR(50),
	`c_res_code` VARCHAR(50) COMMENT '资源代码（头像）',
	CONSTRAINT `pk_c_id` PRIMARY KEY (`c_id`)
) COMMENT='用户表'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `T_S_User` 
 ADD CONSTRAINT `uk_c_user_code` UNIQUE (`c_user_code`)
;

ALTER TABLE `T_S_User` 
 ADD INDEX `idx_c_user_pwd` (`c_user_pwd` ASC)
;

SET FOREIGN_KEY_CHECKS=1;
